### ISSUE TITLE
pyfiglet module issue

### ISSUE THREAD

**Issue by torabi12** [BroadbentT/ZIP-CRACKER#3]
I got this error at startup:
![image](https://user-images.githubusercontent.com/98665813/232225659-2fc2934a-a717-4113-964b-d0a1efa1c6fb.png)

but the module has been installed:
![image](https://user-images.githubusercontent.com/98665813/232225680-bf80b485-5ebc-49db-801f-3a699e639c59.png)

It is on Ubuntu 22.04.2 desktop, could someone help me how to fix his?

**Comment by BroadbentT** [comment]
Uninstall and then try pip3 install pyfiglet.
